[package]
name = "rust-container"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.29.0", features = ["mount", "sched", "process", "fs", "hostname"] }
which = "6.0.1"
