version: '3.8'

services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    platform: linux/amd64
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
      - rust-target:/workspace/target
    security_opt:
      - seccomp:unconfined
    cap_add:
      - ALL
    init: true

volumes:
  rust-target:
